name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V27
      - name: Build & test
        run: nix develop .#stable -c cargo test --workspace --all-features --no-fail-fast
  wasm-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V27
      - name: Test in headless Chrome
        run: nix develop .#wasm -c wasm-pack test --headless --chrome
